[package]
name = "goxlr-profile-loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "*"
enum-map-derive = "*"

strum = "0.23"
strum_macros = "0.23"

ritelinked = "0.3.2"

xml-rs = "0.8"