[package]
name = "goxlr-profile-loader"
version = "1.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-map = "2.7.3"
enum-map-derive = "0.17.0"
thiserror = "1.0.50"
zip = { version = "2.1.5", default-features = false, features = ["deflate"] }
strum = { version = "0.26.3", features = ["derive"] }
ritelinked = "0.3.2"
quick-xml = "0.36.1"
byteorder = "1.5.0"

tempfile = "3.10.1"

anyhow = "1.0.86"
log = "0.4.22"
