[package]
name = "goxlr-launcher"
version = "0.12.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
goxlr-ipc = { path = "../ipc" }
goxlr-types = { path = "../types" }

interprocess = { version = "1.2.1", features=["tokio_support"] }
tokio = { version = "1.23.0", features=["full"] }
which = "4.3.0"

[target.'cfg(windows)'.dependencies]
tasklist = "0.2.12"

[target.'cfg(target_family = "unix")'.dependencies]
nix = "0.26.2"
sysinfo = "0.29.4"

[target.'cfg(target_os = "windows")'.build-dependencies]
windres = "0.2.2"
