[package]
name = "goxlr-scribbles"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.2"
imageproc = "0.25.0"
ab_glyph = "0.2.28"
anyhow = "1.0.86"
log = "0.4.22"
