name: Publish Release Draft
on: workflow_dispatch
jobs:

  # Before we do anything, run the existing test suite..
  verify:
    uses: ./.github/workflows/build.yml

  # Grab the current version..
  get_version:
    uses: ./.github/workflows/get-version.yaml

  # Create and upload release artifacts
  build:
    uses: ./.github/workflows/build-release.yaml

  # Actually Create the Release
  create_release_draft:
    needs: [verify, get_version, build]
    runs-on: ubuntu-latest
    steps:
      # Download the previously generated artifacts..
      - name: Download Artifacts
        uses: actions/download-artifact@v2

      - name: List Downloaded Files..
        run: ls -lahR

      # Create the Draft Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ needs.get_version.outputs.version }}
          tag_name: v${{ needs.get_version.outputs.version }}
          body: 'Put Changelog Here!'
          draft: true
          prerelease: true
          fail_on_unmatched_files: true
          files: |
            ./debian-artifact/goxlr-utility_${{ needs.get_version.outputs.version }}_amd64.deb
            ./rpm-artifact/goxlr-utility-${{ needs.get_version.outputs.version }}-1.x86_64.rpm
            ./windows-artifact/goxlr-utility-${{ needs.get_version.outputs.version }}.exe
